# Use official Node.js image from Docker Hub
FROM node:16

# Set the working directory inside the container
WORKDIR /home/ubuntu/myData/my-node-app

# Copy package.json and package-lock.json first for better caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Command to run the app
CMD ["node", "app.js"]
